version: "3.8"
services:
  pharmacy-recommendation-redis:
    container_name: pharmacy-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: renechoi/pharmacy-recommendation-redis
    ports:
      - "6379:6379"
  pharmacy-recommendation-database:
    container_name: pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: renechoi/pharmacy-recommendation-database
    environment:
      - MARIADB_DATABASE=pharmacy_recommendation
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3307:3306"