spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3308/pharmacy-recommendation
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

pharmacy:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---
spring:
  config:
    activate:
      on-profile: prod
